### ISSUE TITLE
Typo in peer dependency name

### ISSUE THREAD

**Issue by variadicintegrity** [rhysforyou/gatsby-plugin-react-helmet-async#1]
The peer dependency lists:
"react-helmet-asynx": "0.2.x"

But the actual package name should be: "react-helmet-async"

**Comment by behivetech** [comment]
Well, I guess since this has been sitting here since April, I'm going to fork it and make another npm repo.

**Comment by MartinRosenberg** [comment]
I rewrote it in TypeScript and have been actively maintaining it: https://github.com/Collabsalot/gatsby-plugin-react-helmet-async
